### ISSUE TITLE
How to programatically get the FTP URL, given a MassIVE identifier

### ISSUE THREAD

**Issue by wfondrie** [CCMS-UCSD/MassIVEDocumentation#28]
Hi folks 👋 

Recent changes to the MassIVE FTP site organization broke the functionality of my project, [ppx](https://ppx.readthedocs.io/en/latest/) (https://github.com/wfondrie/ppx/issues/30), which strives to make it easy to programmatically access datasets. It seems that projects are now distributed among multiple version subdirectories (currently, I see `v0[1-7]` and `x01`). 

Is there an API endpoint or similar from which I can retrieve the correct FTP URL for a given dataset? I spot checked a few using the PROXY API (`http://massive.ucsd.edu/ProteoSAFe/proxi/v0.1/datasets/<accession>`), but they were incorrect.

For example:
```
https://massive.ucsd.edu/ProteoSAFe/proxi/v0.1/datasets/MSV000094236
```
Returns an FTP link of `ftp://massive.ucsd.edu/MSV000094236` when it is actually `ftp://massive.ucsd.edu/v07/MSV000094236`.

Thanks!

**Comment by jjcarver** [comment]
Thanks for letting us know about this. I know this restructuring has been an inconvenience, and I appreciate your patience with this.

The PROXI /datasets API endpoint should be showing the correct FTP URL. This is a bug that I will fix ASAP. Thank you for bringing this to our attention.

**Comment by wfondrie** [comment]
Thanks for the quick response - I appreciate all the work y'all do!

**Comment by jjcarver** [comment]
@wfondrie This issue is now resolved. The example you provided now returns the correct FTP URL:

`https://massive.ucsd.edu/ProteoSAFe/proxi/v0.1/datasets/MSV000094236`

Please let me know if you see any other issues.
