### ISSUE TITLE
Broken paths to `ccms_peak` files

### ISSUE THREAD

**Issue by wfondrie** [CCMS-UCSD/MassIVEDocumentation#30]
I've been trying to download some of the mzML files used to build MassIVE-KB, but it seems there seems to be a consistent problem for files in the `ccms_peak` directories. For example, here I try to download an mzML file from MSV000088407:

```
$ wget ftp://massive.ucsd.edu/x01/MSV000088407/ccms_peak/RAW/AD02_BA46_INSOLUBLE_01.mzML
--2024-04-24 10:01:14--  ftp://massive.ucsd.edu/x01/MSV000088407/ccms_peak/RAW/AD02_BA46_INSOLUBLE_01.mzML
           => ‘AD02_BA46_INSOLUBLE_01.mzML’
Resolving massive.ucsd.edu (massive.ucsd.edu)... 132.249.211.16
Connecting to massive.ucsd.edu (massive.ucsd.edu)|132.249.211.16|:21... connected.
Logging in as anonymous ... Logged in!
==> SYST ... done.    ==> PWD ... done.
==> TYPE I ... done.  ==> CWD (1) /x01/MSV000088407/ccms_peak/RAW ...
No such directory ‘x01/MSV000088407/ccms_peak/RAW’.
```

If instead I try a different file outside of the `ccms_peak` directory, it works without issue:
```
$ wget ftp://massive.ucsd.edu/x01/MSV000088407/ccms_parameters/params.xml
--2024-04-24 10:07:03--  ftp://massive.ucsd.edu/x01/MSV000088407/ccms_parameters/params.xml
           => ‘params.xml.1’
Resolving massive.ucsd.edu (massive.ucsd.edu)... 132.249.211.16
Connecting to massive.ucsd.edu (massive.ucsd.edu)|132.249.211.16|:21... connected.
Logging in as anonymous ... Logged in!
==> SYST ... done.    ==> PWD ... done.
==> TYPE I ... done.  ==> CWD (1) /x01/MSV000088407/ccms_parameters ... done.
==> SIZE params.xml ... 16688
==> PASV ... done.    ==> RETR params.xml ... done.
Length: 16688 (16K) (unauthoritative)

params.xml.1           100%[===========================>]  16.30K  --.-KB/s    in 0.04s

2024-04-24 10:07:03 (374 KB/s) - ‘params.xml.1’ saved [16688]
```

Please note that the mzML file I'm trying to download is also shown on the webpage, but must be downloaded over FTP:
![image](https://github.com/CCMS-UCSD/MassIVEDocumentation/assets/9124668/827ff496-9c71-4678-9a1f-d78c46d59c61)

Thanks for your help!

**Comment by wfondrie** [comment]
Thanks @jjcarver,

Are the files for every dataset on  volume "z01", or does the drive parallel that of the dataset? For example, if a dataset is now at "x07", would the ccms_peak files be on "z07"? 

It's great to have a source for mzML files that have generated in a homogeneous manner from a large number of datasets!

**Comment by jjcarver** [comment]
@wfondrie That's a good question. Currently there is no mirrored volume naming structure. Volume z01 currently stores all ccms_peak files period, regardless of which volume their associated dataset is stored under.
